name = "MakieBake"
uuid = "a115e09d-244e-4709-8d7d-89753b11a70b"
authors = ["Alexander Plavin <alexander@plav.in>"]
version = "0.1.0"

[deps]
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
MakieExtra = "54e234d5-9986-40d8-815f-a5e42de435f6"
