name = "MakieBake"
uuid = "a115e09d-244e-4709-8d7d-89753b11a70b"
authors = ["Alexander Plavin <alexander@plav.in>"]
version = "0.1.2"

[deps]
AccessorsExtra = "33016aad-b69d-45be-9359-82a41f556fd4"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
MakieExtra = "54e234d5-9986-40d8-815f-a5e42de435f6"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"

[compat]
AccessorsExtra = "0.1"
JSON3 = "1"
MakieExtra = "0.1"
ProgressMeter = "1"
julia = "1.10"
